# MLFlow

mlflow:
    _target_: pytorch_lightning.loggers.MLFlowLogger
    experiment_name: "Evaluate_MCD_OoD_detection"
    tags:
        stage: evaluation
        dropout: True
        dropout_location: "box head"
        vos: False

    tracking_uri: "file:${work_dir}/mlruns"