_BASE_: "../Base-Inference.yaml"

PROBABILISTIC_INFERENCE:
    # One of the following: 'standard_nms', 'mc_dropout_ensembles',
    # 'anchor_statistics', 'bayes_od', 'ensemble'
    INFERENCE_MODE: 'standard_nms'

    MC_DROPOUT:
        # Enables MC_Dropout if INFERENCE_MODE supports it.
        # After inference: perform MC dropout after a normal inference pass (default option for TDL project)
        AFTER_INFERENCE: True
        ENABLE: True
        NUM_RUNS: 10
        # Layer_type is either 'FC' (Fully Connected for a normal dropout leyer), or
        # 'Conv' (Convolutional for a Dropblock layer)
        LAYER_TYPE: 'FC'

    # Either 'openimages_ood_val' for openimages OoD or 'coco_ood_val_bdd'
    OOD_DATASET: "openimages_ood_val"