# @package _global_

# default configuration
defaults:
    - _self_
    - logger: mlflow.yaml

    # enable color logging
    # - override hydra/hydra_logging: colorlog
    # - override hydra/job_logging: colorlog

work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/MCD_evaluation_data/
log_dir: logs_hydra/runs/${logger.mlflow.experiment_name}/${now:%Y-%m-%d_%H-%M-%S}

# Datasets
ood_dataset: "coco"
bdd_valid_mcd_samples: "bdd_valid_8000_1000_10_mcd_samples.pt"
bdd_test_mcd_samples: "bdd_test_2000_1000_10_mcd_samples.pt"
ood_mcd_samples: "coco_ood_test_1880_1000_10_mcd_samples.pt"
# Precomputed entropies
bdd_entropy_valid: "bdd_valid_8000_1000_10_MCD_h_z_samples.npy"
bdd_entropy_test: "bdd_test_2000_1000_10_MCD_h_z_samples.npy"
ood_entropy_test: "coco_ood_test_1880_1000_10_MCD_h_z_samples.npy"
# Eval configuration
precomputed_mcd_runs: 10
# Number of Monte Carlo Dropout runs to use.
n_mcd_runs: 10
# This parameter controls the raw number of proposals from RPN to be used.
# If it is <1000, a random sampler will take that number of samples to continue with the rest of the algorithm
use_n_proposals: 1000
n_pca_components: [1, 2, 3, 4, 6, 8, 10, 12]
n_pacmap_neighbors: 10
n_pacmap_components: [2, 3, 4, 5, 6, 8, 10, 12]
normalize_kde_prediction: False
seed: 42

hydra:
    # output paths for hydra logs
    run:
        dir: ${log_dir}

    sweep:
        dir: logs_hydra/multiruns/${now:%Y-%m-%d_%H-%M-%S}
        subdir: ${hydra.job.num}
