dropblock: True
extra_fc: False
dropout: False
fifth_conv_layer: False
sn: True
half_sn: False
activation: "leaky"
normalize_inputs: False
dropblock_prob: 0.3
dropblock_size: 1
dropout_prob: 0.5
avg_pool: True
# dropblock location at the output of the nth residual layer
dropblock_location: 3