dropblock: True
extra_fc: False
dropout: False
fifth_conv_layer: False
sn: False
half_sn: True
activation: "leaky"
cifar10_normalize_inputs: False
dropblock_prob: 0.5
dropblock_size: 3
dropout_prob: 0.5
avg_pool: True
# dropblock location at the output of the nth residual layer
dropblock_location: 2
image_size: 32